base: &base
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  database: cymes_developemnt
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  host: db

development:
  <<: *base

test:
  <<: *base
  database: cymes_developemnt
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  host: db


remote_development:
  <<: *base
  database: fae_dev
  username: fae
  password: sh45&rEDnap

stage:
  <<: *base
  database: fae_stage
  username: fae
  password: sh45&rEDnap

production:
  <<: *base
  database: fae
  username: fae
  password: sh45&rEDnap
